dataset:
    hg38

fasta:
    url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
    type: gz
    name: genome.fa.gz

chrom_size:
    url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chrom.sizes
    type: plain
    name: genome.chrom.sizes

ref_flat:
    url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refFlat.txt.gz
    type: gz-no-unpack
    name: refFlat.csv.gz
    postprocess: refFlat

gencode_exon:
    url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/gencode.v47.annotation.gtf.gz
    type: gz
    name: gencode.csv.gz
    postprocess: gencode

gencode_intron:
    url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/wgEncodeGencodeAutoV47.txt.gz
    type: gz
    name: gencode_intron.bed.gz

est:
    url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/intronEst.txt.gz
    type: gz
    name: est.bed.gz
