name: API Health Check

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  check-ensembl:
    name: Ensembl REST health check
    runs-on: ubuntu-latest
    steps:
      - name: Ping Ensembl /info/ping with retries
        id: health
        shell: bash
        run: |
          set -euo pipefail
          url="https://rest.ensembl.org/info/ping?content-type=application/json"

          ok="false"
          for i in $(seq 1 12); do
            status=$(curl -sS -m 10 -w "%{http_code}" -o ping.json "$url" || echo "000")
            if [ "$status" = "200" ] && grep -Eq '"ping"[[:space:]]*:[[:space:]]*1' ping.json; then
              ok="true"
              break
            fi
            sleep $((i * 5))
          done

          if [ "$ok" = "true" ]; then
            echo "✅ Ensembl API is up"
          else
            echo "❌ Ensembl API is down"
            exit 1
          fi

  check-ucsc:
    name: UCSC Genome Browser health check
    runs-on: ubuntu-latest
    steps:
      - name: HEAD request to UCSC chain file with retries
        id: ucsc
        shell: bash
        run: |
          set -euo pipefail
          url="http://hgdownload.cse.ucsc.edu/goldenPath/mm10/liftOver/mm10ToHg38.over.chain.gz"

          ok="false"
          for i in $(seq 1 12); do
            status=$(curl -sS -m 10 -I -w "%{http_code}" -o /dev/null "$url" || echo "000")
            if [ "$status" = "200" ]; then
              ok="true"
              break
            fi
            sleep $((i * 5))
          done

          if [ "$ok" = "true" ]; then
            echo "✅ UCSC Genome Browser is up"
          else
            echo "❌ UCSC Genome Browser is down"
            exit 1
          fi

  check-blast:
      name: NCBI BLAST API health check
      runs-on: ubuntu-latest
      steps:
        - name: HEAD request to NCBI BLAST with retries
          id: blast
          shell: bash
          run: |
            set -euo pipefail
            url="https://blast.ncbi.nlm.nih.gov/Blast.cgi"

            ok="false"
            for i in $(seq 1 12); do
              status=$(curl -sS -m 10 -I -w "%{http_code}" -o /dev/null "$url" || echo "000")
              if [ "$status" = "200" ]; then
                ok="true"
                break
              fi
              sleep $((i * 5))
            done

            if [ "$ok" = "true" ]; then
              echo "✅ NCBI BLAST API is up"
            else
              echo "❌ NCBI BLAST API is down"
              exit 1
            fi
