name: circtools pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: '0 11 * * *'

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: false

jobs:
  Main:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        R: ['4.4.0']
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: R ${{ matrix.R }} | Python ${{ matrix.python-version }} | ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install numpy wheel Cython
        sudo apt-get update && sudo apt-get install -y libblas-dev libatlas-base-dev liblapack-dev
        python -m pip install ./

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}

    - name: Set up R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          local::circtools/contrib/circtest
          local::circtools/contrib/primex

    - name: Check R library loading
      run: Rscript -e 'library(primex)'

    - name: Check circtools is callable
      run: |
        circtools --version
        which circtools

    - name: Download test data
      run: |
        tar xvf circtools_example.tar.bz2

    - name: Run circtools detect
      run: |
        cd circtools_example
        circtools detect @samplesheet -ss -T 2 -D \
          -an chr1.gtf -A chr1.fa -B @bam_files.txt -M -Nr 5 6 -G -F -L 20 -O circtools_ci -k

    - name: Fix missing Strand column (if needed)
      run: |
        cd circtools_example/circtools_ci
        if [ "$(head -n1 LinearCount | awk -F'\t' '{sum=0; for(i=1;i<=NF;i++) if($i=="Strand") sum++; print sum}')" -eq 0 ]; then
          echo "➕ Adding missing Strand column..."
          awk 'BEGIN {OFS=FS="\t"}
               NR==1 {
                 for (i=1; i<=NF; i++) {
                   if (i==4) printf "Strand%s", OFS;
                   printf "%s%s", $i, (i<NF ? OFS : ORS)
                 }
                 next
               }
               {
                 for (i=1; i<=NF; i++) {
                   if (i==4) printf "+%s", OFS;
                   printf "%s%s", $i, (i<NF ? OFS : ORS)
                 }
               }' LinearCount > LinearCount_fixed && mv LinearCount_fixed LinearCount
        else
          echo "✅ Strand column already exists — skipping."
        fi

    - name: Run circtest
      run: |
        cd circtools_example
        circtools circtest \
          -d ./circtools_ci/ \
          -c 5,6,7 \
          -g 2,1,1 \
          -l control,treatment \
          -r 3 \
          -f 0.9 \
          -p 0.01 \
          -s 1 \
          -C 1 \
          -o ./circtest_output \
          -n test_output \
          -M bw

    - name: Run conservation
      run: |
        cd circtools_example
        mkdir -p conservation/temp
        circtools conservation \
          -d ./circtools_ci/CircCoordinates \
          -f ./chr1.fa \
          -g ./chr1.gtf \
          -O mm \
          -G Map3k5 \
          -o ./conservation/ \
          -t ./conservation/temp/ \
          -TS hs \
          -pairwise

    - name: Run padlock
      run: |
        cd circtools_example
        mkdir -p padlock_output
        circtools padlock \
          -f ./chr1.fa \
          -g ./chr1.gtf \
          -O mm \
          -G Slc16a9 \
          -T Slc16a9_padlock_design \
          -r 1 \
          -b \
          -o ./padlock_output

    - name: Run primex
      run: |
        cd circtools_example
        mkdir -p primer_output
        circtools primex \
          -d ./circtools_ci/CircCoordinates \
          -f ./chr1.fa \
          -g ./chr1.gtf \
          -O mm \
          -G Slc16a9 \
          -T "Slc16a9_primer" \
          -o ./primer_output
