name: circtools nanopore (docker)

on:
  push:

concurrency:
  group: ci-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_IMAGE: ghcr.io/jakobilab/circtools:master

jobs:
  run-nanopore-docker:
    name: circtools nanopore (Docker)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Pull image
        run: |
          docker pull "${GHCR_IMAGE}"
          docker image inspect "${GHCR_IMAGE}" --format '{{json .RepoTags}}'

      - name: Unpack test dataset
        run: |
          tar xvf ./tests/data/circtools_example.tar.bz2
          cd circtools_example
          # Ensure genome + annotation are uncompressed
          if [ -f genome.fa.gz ]; then gunzip -f genome.fa.gz; fi
          if [ -f annotation.gtf.gz ]; then gunzip -f annotation.gtf.gz; fi
          ls -lh

      - name: Subsample nanopore data
        run: |
          cd circtools_example
          # Copy human nanopore dataset from repo
          cp ../tests/data/human_nanopore.fastq.gz .
          # Extract first 1M reads (4M lines)
          zcat human_nanopore.fastq.gz | head -n 4000000 | gzip > human_nanopore_1M.fastq.gz
          ls -lh human_nanopore_1M.fastq.gz

      - name: Download reference data
        run: |
          cd circtools_example
          docker run --rm \
            -v "$(pwd):/host_rel/" \
            -w /host_rel \
            "${GHCR_IMAGE}" \
            nanopore \
              -d \
              -R reference/ \
              -C hg38

      - name: Run circtools nanopore (Docker)
        run: |
          cd circtools_example
          mkdir -p results
          docker run --rm \
            -v "$(pwd):/host_rel/" \
            -w /host_rel \
            "${GHCR_IMAGE}" \
            nanopore \
              -r \
              -s human_nanopore_1M.fastq.gz \
              -R reference/ \
              -C hg38 \
              -O results/ \
              --threads 16

      - name: Upload circRNA candidates artifact
        uses: actions/upload-artifact@v4
        with:
          name: circRNA-candidates
          path: circtools_example/results/human_nanopore_1M.circRNA_candidates.annotated.txt
