name: circtools circtest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 11 * * *'

concurrency:
  group: ci-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Main:
    strategy:
      matrix:
        os: [ macos-13, macos-15,ubuntu-24.04 ]
        R:  ['4.4.0', '4.5.1' ]
        python-version: [ "3.9", "3.10", "3.11"]
    name: R ${{ matrix.R }} | Python ${{ matrix.python-version }} | ${{ matrix.os }}
    steps:
    - name: Create files
      uses: actions/checkout@v4
      with:
       ref: wjm2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Updating setuptools
      run: |
         python3 -m pip install -U pip setuptools
    - name: Installing circtools & Python dependencies
      run: |
         if [ "$RUNNER_OS" == "Linux"]; then
            apt-get install libblas-dev libatlas-base-dev liblapack-dev -y
         fi
         if [ "$RUNNER_OS" == "macOS"]; then
            export SYSTEM_VERSION_COMPAT=1
            sudo rm -rf /Library/Developer/CommandLineTools
            sudo xcode-select --install
            python3 -m pip install ./
         else
            python3 -m pip install ./
         fi
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    - name: Set up R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          local::circtools/contrib/circtest
          local::circtools/contrib/primex
    - name: Checking library loading
      run: Rscript -e 'library(primex)'
    - name: Check if circtools starts
      run: |
         circtools --version
         which circtools
    - name: Downloading circtools detect test data
      run: |
        tar xvf ./tests/data/circtools_example.tar.bz2
    - name: Fix missing Strand column (if needed)
      run: |
        cd circtools_example/circtools_ci_master
        if [ "$(head -n1 LinearCount | awk -F'\t' '{sum=0; for(i=1;i<=NF;i++) if($i=="Strand") sum++; print sum}')" -eq 0 ]; then
          echo "➕ Adding missing Strand column..."
          awk 'BEGIN {OFS=FS="\t"}
               NR==1 {
                 for (i=1; i<=NF; i++) {
                   if (i==4) printf "Strand%s", OFS;
                   printf "%s%s", $i, (i<NF ? OFS : ORS)
                 }
                 next
               }
               {
                 for (i=1; i<=NF; i++) {
                   if (i==4) printf "+%s", OFS;
                   printf "%s%s", $i, (i<NF ? OFS : ORS)
                 }
               }' LinearCount > LinearCount_fixed && mv LinearCount_fixed LinearCount
        else
          echo "✅ Strand column already exists — skipping."
        fi

    - name: Run circtest
      run: |
        cd circtools_example
        circtools circtest \
          -d ./circtools_ci_master/ \
          -c 5,6,7 \
          -g 2,1,1 \
          -l control,treatment \
          -r 3 \
          -f 0.9 \
          -p 0.01 \
          -s 1 \
          -C 1 \
          -o ./circtest_output \
          -n test_output \
          -M bw

    - name: Checking generated output against master output
      run: |
        cd circtools_example/circtest_output
        ls -la
        wc -l *

        if [ "$RUNNER_OS" = "Linux" ]; then
          MASTER_DIR="../circtest_output_master"
          diff test_output.csv "$MASTER_DIR/test_output.csv"
          sha1sum -c "$MASTER_DIR/sha1sums.txt"
        elif [ "$RUNNER_OS" = "macOS" ] && [ "${{ matrix.os }}" = "macos-13" ]; then
          MASTER_DIR="../circtest_output_master_mac_amd"
          diff test_output.csv "$MASTER_DIR/test_output.csv"
          shasum -a 1 -c "$MASTER_DIR/sha1sums.txt"
        elif [ "$RUNNER_OS" = "macOS" ]; then
          MASTER_DIR="../circtest_output_master_mac"
          diff test_output.csv "$MASTER_DIR/test_output.csv"
          shasum -a 1 -c "$MASTER_DIR/sha1sums.txt"
        else
          echo "Unsupported OS: $RUNNER_OS" >&2
          exit 1
        fi


    runs-on: ${{ matrix.os }}

